server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://172.19.240.197:53306/agiledb?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:daoImpl/*Mapper.xml
  type-aliases-package: com.bolingcavalry.mavendockerplugindemo.PO